### ISSUE TITLE
Creating given entities and their respective factories and test classes

### ISSUE THREAD

**Issue by DominicPrzygonski** [DominicPrzygonski/school_management#1]
Completing question 1 and 2 of the project

**Comment by siwe-cput** [comment]
On domain I can't see entities assigned to me.....
________________________________

**Comment by siwe-cput** [comment]
Then are not suppose to show up as updated my branches n sent pull request....

Adding my domain won't mess up the project now?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
