### ISSUE TITLE
Creating repositories and services for given entities

### ISSUE THREAD

**Issue by DominicPrzygonski** [DominicPrzygonski/school_management#2]
Completing question 3 and 4 of the project

**Comment by siwe-cput** [comment]
hallo Sir I have sent a pull request,


________________________________
From: Dom ***@***.***>
Sent: Tuesday, June 14, 2022 12:34 PM
To: DominicPrzygonski/school_management ***@***.***>
Cc: Andisiwe Qhuva ***@***.***>; Assign ***@***.***>
Subject: [DominicPrzygonski/school_management] Creating repositories and services for given entities (Issue #2)


Completing question 3 and 4 of the project

**Comment by siwe-cput** [comment]
Hallo sir I've been trying pull request but It doesn't allow me to do so as the project is updated. In the the compare n request there's nothing to compare with.


Does this mean I should continue with other questions or I  cannot contribute at all to the project as I am behind?.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
